### ISSUE TITLE
how to tune k_a, k_mu?

### ISSUE THREAD

**Issue by qynino** [cpezzato/panda_simulation#3]
I have try your code in the other robot but can not find right k_a or k_mu

**Comment by cpezzato** [comment]
Hi! I have to say it takes some practice. What I usually so is to start with no actions (i.e. ka = 0), then tune k_mu for decent convergent behavior to the senses states. Then I start increasing ka. Depending on your robot, you might want to have a value for ever joint separately. Where the  last joints have lower values, since have less mass and inertia.

Hope this help!
